/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante.gui.pedido;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JRadioButton;
import restaurante.dados.cardapio.Item;
import restaurante.dados.pedido.Pedido;
import restaurante.dados.pedido.PedidoBalcao;
import restaurante.dados.pedido.PedidoEntrega;
import restaurante.dados.pedido.PedidoMesa;

import restaurante.exception.ItemJaExistenteException;
import restaurante.fachada.Fachada;

/**
 * @author Lucas
 * @author Gustavo
 * @author Carlos Henrique
 * @author Joao Victor
 */
public class TelaNovoPedido extends javax.swing.JFrame {

    /**
     * Creates new form TelaNovoPedido
     */
    private String categoriaPedido;
    private String mesa;
    private DefaultListModel model1 = new DefaultListModel();
    private DefaultListModel model2 = new DefaultListModel();
    private String item=null;
    private double valorTotal = 0;
    
    public TelaNovoPedido()  {
        initComponents();
//        try {
//            Fachada.getInstancia().lerCardapio();
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(TelaNovoPedido.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ItemJaExistenteException ex) {
//            Logger.getLogger(TelaNovoPedido.class.getName()).log(Level.SEVERE, null, ex);
//        }
        listaEntradas.setListData(Fachada.getInstancia().listarItensCategoria("entradas"));
        listaPrecoEntradas.setListData(Fachada.getInstancia().listarPrecosCategoria("entradas"));
        listaPratos.setListData(Fachada.getInstancia().listarItensCategoria("pratos"));
        listaPrecoPratos.setListData(Fachada.getInstancia().listarPrecosCategoria("pratos"));
        listaSobremesas.setListData(Fachada.getInstancia().listarItensCategoria("sobremesas"));
        listaPrecoSobremesas.setListData(Fachada.getInstancia().listarPrecosCategoria("sobremesas"));
        listaBebidas.setListData(Fachada.getInstancia().listarItensCategoria("bebidas"));
        listaPrecoBebidas.setListData(Fachada.getInstancia().listarPrecosCategoria("bebidas"));
        this.categoriaPedido = "balcao";
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ImageIcon icon = new ImageIcon("src/imagens/menu.png");
        icon.setImage(icon.getImage().getScaledInstance(50, 50, 100));
        icone.setIcon(icon);
       this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        abas = new javax.swing.JTabbedPane();
        abaEntradas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEntradas = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaPrecoEntradas = new javax.swing.JList<>();
        abaPratos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPratos = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaPrecoPratos = new javax.swing.JList<>();
        abaSobremesas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaSobremesas = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaPrecoSobremesas = new javax.swing.JList<>();
        abaBebidas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaBebidas = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        listaPrecoBebidas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rdtipoMesa = new javax.swing.JRadioButton();
        rdtipoBalcao = new javax.swing.JRadioButton();
        rdtipoEntrega = new javax.swing.JRadioButton();
        boxMesas = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaAdicionados = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        listaValores = new javax.swing.JList<>();
        txtValor = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        icone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo Pedido");

        listaEntradas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaEntradas);

        listaPrecoEntradas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Fachada.getInstancia().listarPrecosCategoria("entradas");
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(listaPrecoEntradas);

        javax.swing.GroupLayout abaEntradasLayout = new javax.swing.GroupLayout(abaEntradas);
        abaEntradas.setLayout(abaEntradasLayout);
        abaEntradasLayout.setHorizontalGroup(
            abaEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaEntradasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );
        abaEntradasLayout.setVerticalGroup(
            abaEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addComponent(jScrollPane8)
        );

        abas.addTab("Entradas", abaEntradas);

        jScrollPane2.setViewportView(listaPratos);

        jScrollPane7.setViewportView(listaPrecoPratos);

        javax.swing.GroupLayout abaPratosLayout = new javax.swing.GroupLayout(abaPratos);
        abaPratos.setLayout(abaPratosLayout);
        abaPratosLayout.setHorizontalGroup(
            abaPratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaPratosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );
        abaPratosLayout.setVerticalGroup(
            abaPratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addComponent(jScrollPane7)
        );

        abas.addTab("Pratos", abaPratos);

        jScrollPane3.setViewportView(listaSobremesas);

        jScrollPane5.setViewportView(listaPrecoSobremesas);

        javax.swing.GroupLayout abaSobremesasLayout = new javax.swing.GroupLayout(abaSobremesas);
        abaSobremesas.setLayout(abaSobremesasLayout);
        abaSobremesasLayout.setHorizontalGroup(
            abaSobremesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaSobremesasLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );
        abaSobremesasLayout.setVerticalGroup(
            abaSobremesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addComponent(jScrollPane5)
        );

        abas.addTab("Sobremesas", abaSobremesas);

        jScrollPane4.setViewportView(listaBebidas);

        jScrollPane6.setViewportView(listaPrecoBebidas);

        javax.swing.GroupLayout abaBebidasLayout = new javax.swing.GroupLayout(abaBebidas);
        abaBebidas.setLayout(abaBebidasLayout);
        abaBebidasLayout.setHorizontalGroup(
            abaBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaBebidasLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );
        abaBebidasLayout.setVerticalGroup(
            abaBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
        );

        abas.addTab("Bebidas", abaBebidas);

        jLabel1.setText("Selecione os itens do pedido:");

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de pedido:");

        buttonGroup1.add(rdtipoMesa);
        rdtipoMesa.setText("Mesa");
        rdtipoMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtipoMesaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdtipoBalcao);
        rdtipoBalcao.setSelected(true);
        rdtipoBalcao.setText("Balcão");
        rdtipoBalcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtipoBalcaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdtipoEntrega);
        rdtipoEntrega.setText("Entrega");
        rdtipoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtipoEntregaActionPerformed(evt);
            }
        });

        boxMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mesa 1", "Mesa 2", "Mesa 3", "Mesa 4","Mesa 5","Mesa 6","Mesa 7","Mesa 8","Mesa 9","Mesa 10","Mesa 11","Mesa 12","Mesa 14","Mesa 15","Mesa 16","Mesa 17","Mesa 18","Mesa 19","Mesa 20","Mesa 21","Mesa 22","Mesa 23","Mesa 24","Mesa 25","Mesa 26","Mesa 27","Mesa 28","Mesa 29","Mesa 30" }));
        boxMesas.setEnabled(false);
        boxMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMesasActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jScrollPane9.setViewportView(listaAdicionados);

        jLabel3.setText("Itens Selecionados");

        txtTotal.setText("Total:");

        jScrollPane10.setViewportView(listaValores);

        txtValor.setBackground(new java.awt.Color(153, 153, 255));
        txtValor.setText("$$$$$");
        txtValor.setOpaque(true);

        btnAdicionar.setText("Adicionar Item");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover item");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        icone.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(abas, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdtipoMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdtipoBalcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdtipoEntrega))
                    .addComponent(boxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFinalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(icone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abas, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnAdicionar)
                            .addComponent(btnRemover)
                            .addComponent(btnFinalizar)
                            .addComponent(txtTotal)
                            .addComponent(txtValor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdtipoMesa)
                            .addComponent(rdtipoBalcao)
                            .addComponent(rdtipoEntrega))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void rdtipoMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtipoMesaActionPerformed
        // TODO add your handling code here:
        boxMesas.setEnabled(true);
        this.categoriaPedido = "mesa";
    }//GEN-LAST:event_rdtipoMesaActionPerformed

    private void rdtipoBalcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtipoBalcaoActionPerformed
        // TODO add your handling code here:
        boxMesas.setEnabled(false);
        this.categoriaPedido = "balcao";
    }//GEN-LAST:event_rdtipoBalcaoActionPerformed

    private void rdtipoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtipoEntregaActionPerformed
        // TODO add your handling code here:
        boxMesas.setEnabled(false);
        this.categoriaPedido = "entrega";
    }//GEN-LAST:event_rdtipoEntregaActionPerformed

    private void boxMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMesasActionPerformed
        // TODO add your handling code here:
        this.mesa = (String) boxMesas.getSelectedItem();
    }//GEN-LAST:event_boxMesasActionPerformed

    /**
     * Metodo que insere um pedido no repositorio e atualiza a lista de pedidos
     * @param evt
     */
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        if(listaAdicionados.getModel().getSize()!=0)
        {
        if (categoriaPedido.equals("mesa")) {
            Pedido p = new PedidoMesa(mesa);
            Fachada.getInstancia().inserirPedido(p);
            for (int i = 0; i < model1.getSize(); i++) {

                for (Item item : Fachada.getInstancia().listarItensArray()) {

                    if (model1.get(i).equals(item.getNome())) {
                        p.inserirItem(item);

                    }
                }
            }
        } else if (categoriaPedido.equals("balcao")) {

            Pedido k = new PedidoBalcao();
            Fachada.getInstancia().inserirPedido(k);
            for (int i = 0; i < model1.getSize(); i++) {

                for (Item item : Fachada.getInstancia().listarItensArray()) {

                    if (model1.get(i).equals(item.getNome())) {
                        k.inserirItem(item);

                    }
                }
            }
        } else if (categoriaPedido.equals("entrega")) {

            Pedido j = new PedidoEntrega();
            Fachada.getInstancia().inserirPedido(j);
            for (int i = 0; i < model1.getSize(); i++) {

                for (Item item : Fachada.getInstancia().listarItensArray()) {

                    if (model1.get(i).equals(item.getNome())) {
                        j.inserirItem(item);

                    }
                }
            }
            
            
    }
        TelaPedido.getInstancia().atualizaLista();
        dispose();
    }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * Metodo que adiciona itens ao pedido
     * @param evt
     */
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
       
        if (abas.getSelectedComponent()==abaEntradas) {
                item = listaEntradas.getSelectedValue();
           
        }
        else if (abas.getSelectedComponent()==abaPratos) {
         
                item = listaPratos.getSelectedValue();
            
        }
        else if (abas.getSelectedComponent()==abaSobremesas) {
           
                item = listaSobremesas.getSelectedValue();
        }
        else if (abas.getSelectedComponent()==abaBebidas) {
           
                item = listaBebidas.getSelectedValue();
        }
       
        if(item!=null){ 
       model1.addElement(item);
       listaAdicionados.setModel(model1);
       for(Item i : Fachada.getInstancia().listarItensArray())
       {
           if(i.getNome().equals(item))
           {
               model2.addElement(i.getValor());
               valorTotal = valorTotal +i.getValor();
               break;
           }
       }
       listaValores.setModel(model2);
       txtValor.setText(String.valueOf(valorTotal));
       }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * Metodo que remove itens do pedido
     * @param evt
     */
    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        item = listaAdicionados.getSelectedValue();
        for(Item i : Fachada.getInstancia().listarItensArray())
       {
           if(i.getNome().equals(item))
           {
               model2.removeElement(i.getValor());
               valorTotal = valorTotal - i.getValor();
               break;
           }
       }
       listaValores.setModel(model2);
        model1.removeElement(listaAdicionados.getSelectedValue());
        listaAdicionados.setModel(model1);
        txtValor.setText(String.valueOf(valorTotal));
       
    }//GEN-LAST:event_btnRemoverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaBebidas;
    private javax.swing.JPanel abaEntradas;
    private javax.swing.JPanel abaPratos;
    private javax.swing.JPanel abaSobremesas;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JComboBox<String> boxMesas;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel icone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList<String> listaAdicionados;
    private javax.swing.JList<String> listaBebidas;
    private javax.swing.JList<String> listaEntradas;
    private javax.swing.JList<String> listaPratos;
    private javax.swing.JList<String> listaPrecoBebidas;
    private javax.swing.JList<String> listaPrecoEntradas;
    private javax.swing.JList<String> listaPrecoPratos;
    private javax.swing.JList<String> listaPrecoSobremesas;
    private javax.swing.JList<String> listaSobremesas;
    private javax.swing.JList<String> listaValores;
    private javax.swing.JRadioButton rdtipoBalcao;
    private javax.swing.JRadioButton rdtipoEntrega;
    private javax.swing.JRadioButton rdtipoMesa;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnFinalizar() {
        return btnFinalizar;
    }

    public JLabel getTxtValor() {
        return txtValor;
    }

    public void setTxtValor(JLabel txtValor) {
        this.txtValor = txtValor;
    }

    public JList<String> getListaAdicionados() {
        return listaAdicionados;
    }

    public void setListaAdicionados(JList<String> listaAdicionados) {
        this.listaAdicionados = listaAdicionados;
    }

    public JList<String> getListaValores() {
        return listaValores;
    }

    public void setListaValores(JList<String> listaValores) {
        this.listaValores = listaValores;
    }

    public JRadioButton getRdtipoBalcao() {
        return rdtipoBalcao;
    }

    public void setRdtipoBalcao(JRadioButton rdtipoBalcao) {
        this.rdtipoBalcao = rdtipoBalcao;
    }

    public JRadioButton getRdtipoEntrega() {
        return rdtipoEntrega;
    }

    public void setRdtipoEntrega(JRadioButton rdtipoEntrega) {
        this.rdtipoEntrega = rdtipoEntrega;
    }

    public JRadioButton getRdtipoMesa() {
        return rdtipoMesa;
    }

    public void setRdtipoMesa(JRadioButton rdtipoMesa) {
        this.rdtipoMesa = rdtipoMesa;
    }

    public void setBtnFinalizar(JButton btnFinalizar) {
        this.btnFinalizar = btnFinalizar;
    }
}
